### ISSUE TITLE
Checking content_marketing.py shows api info

### ISSUE THREAD

**Issue by piranhap** [kavithacd/DigiMarketing_Crew#1]
Hi! Not really a super knoweledgeable person when it comes to Ghub, but I checked the code for your content_marketing.py script and it seems that it shows your OpenAI API ~ not sure if that is supposed to be there but just wanted to let you know in case it is not supposed to be there :) 
I would love to see some videos on creating like a full content creation crew to make content creation more efficient. thanks!

**Comment by kavithacd** [comment]
Thank you for letting me know. I have already revoked it!
